---
- name: ensure a list of base packages installed
  yum:
    name: "{{ base_packages }}"

- name: ensure a list of additional packages installed
  yum:
    name: "{{ additional_packages }}"

- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
